In [43]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [44]:
from google.colab import files
uploaded = files.upload()

Saving bank_note_data.txt to bank_note_data (1).txt


In [45]:
data = uploaded['bank_note_data.txt']

from numpy import genfromtxt
data = genfromtxt('bank_note_data.txt', delimiter=',')

# .decode("utf-8").split("\r\n")
# for i in range(len(data)):
#   data[i] = data[i].split(",")

data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [46]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [47]:
features = data[:,:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [48]:
X = features
y = labels

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [51]:
from sklearn.preprocessing import MinMaxScaler

In [52]:
scaled_object = MinMaxScaler()
scaled_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [53]:
scaled_x_train = scaled_object.transform(X_train)
scaled_x_test = scaled_object.transform(X_test)

In [54]:
from keras.models import Sequential
from keras.layers import Dense

In [55]:
model = Sequential()

model.add(Dense(4,input_dim = 4,activation='relu'))
model.add(Dense(8,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))

In [57]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [58]:
model.fit(X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 0s - loss: 0.6768 - accuracy: 0.7095
Epoch 2/50
29/29 - 0s - loss: 0.5520 - accuracy: 0.7399
Epoch 3/50
29/29 - 0s - loss: 0.4810 - accuracy: 0.7606
Epoch 4/50
29/29 - 0s - loss: 0.4338 - accuracy: 0.8444
Epoch 5/50
29/29 - 0s - loss: 0.3979 - accuracy: 0.8498
Epoch 6/50
29/29 - 0s - loss: 0.3671 - accuracy: 0.8564
Epoch 7/50
29/29 - 0s - loss: 0.3410 - accuracy: 0.8651
Epoch 8/50
29/29 - 0s - loss: 0.3175 - accuracy: 0.8727
Epoch 9/50
29/29 - 0s - loss: 0.2966 - accuracy: 0.8803
Epoch 10/50
29/29 - 0s - loss: 0.2783 - accuracy: 0.8857
Epoch 11/50
29/29 - 0s - loss: 0.2612 - accuracy: 0.8901
Epoch 12/50
29/29 - 0s - loss: 0.2454 - accuracy: 0.8966
Epoch 13/50
29/29 - 0s - loss: 0.2307 - accuracy: 0.8999
Epoch 14/50
29/29 - 0s - loss: 0.2168 - accuracy: 0.9075
Epoch 15/50
29/29 - 0s - loss: 0.2049 - accuracy: 0.9151
Epoch 16/50
29/29 - 0s - loss: 0.1911 - accuracy: 0.9249
Epoch 17/50
29/29 - 0s - loss: 0.1789 - accuracy: 0.9325
Epoch 18/50
29/29 - 0s - loss: 0.1673 - 

In [63]:
#Let us start predicting now!

predictions = model.predict_classes(scaled_x_test)

In [64]:
#Evaluating the model's performance !

model.metrics_names

['loss', 'accuracy']

In [65]:
model.evaluate(x=scaled_x_test,y=y_test)

15/15 [==============================] - 0s 2ms/step - loss: 0.4594 - accuracy: 0.9426


[0.4594143033027649, 0.9426048398017883]

In [66]:
from sklearn.metrics import confusion_matrix,classification_report

In [67]:
confusion_matrix(y_test,predictions)

array([[257,   0],
       [ 26, 170]])

In [68]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.91      1.00      0.95       257
         1.0       1.00      0.87      0.93       196

    accuracy                           0.94       453
   macro avg       0.95      0.93      0.94       453
weighted avg       0.95      0.94      0.94       453

